services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-rails_password}
      MYSQL_DATABASE: iris_systems_rec_task_development
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10

  web:
    build: .
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-rails_password}
    expose:
      - 3000
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
  
  web1:
    build: .
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-rails_password}
    expose:
      - 3000
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]

  web2:
    build: .
    working_dir: /app
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-rails_password}
    expose:
      - 3000
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3000"]
  
  nginx:
    image: nginx:1.29.5-alpine-slim
    depends_on:
      - web
      - web1
      - web2
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  prometheus:
  # Cannot distroless this as a specific version of distroless is unavailable, but we can pin the version of prometheus itself
    image: prom/prometheus:v3.9.1
    expose:
      - 9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  
  cadvisor:
    image: ghcr.io/google/cadvisor:0.56.2
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - web
      - web1
      - web2

  mysqld-exporter:
    image: prom/mysqld-exporter:v0.18.0
    expose:
      - 9104
    environment:
      DATA_SOURCE_NAME: "root:${MYSQL_PASSWORD:-rails_password}@tcp(db:3306)/"
    depends_on:
      - db

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.5.1
    expose:
      - 9113
    environment:
      NGINX_STATUS_URL: "http://nginx/nginx_status"
    depends_on:
      - nginx

  grafana:
    image: grafana/grafana:12.4.0-21693836646
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

volumes:
  db_data:
  grafana_data:
